### ISSUE TITLE
counts_Lake.Rds

### ISSUE THREAD

**Issue by r3fang** [aertslab/cisTopic#1]
Hello, is it possible to share counts_Lake.Rds file?
Thanks!

**Comment by cbravo93** [comment]
Hi Rongxin!

You can find it at: http://scenic.aertslab.org/cisTopic/counts_Lake.Rds. Let me know if you need anything else.

Cheers!

**Comment by r3fang** [comment]
Thanks!! Do you think it is possible to also share the labels of the cells as shown in the manuscript?

**Comment by cbravo93** [comment]
You can find now the annotation dataframe at:  http://scenic.aertslab.org/cisTopic/cellData_Lake.Rds .

Cheers!

**Comment by r3fang** [comment]
Thanks!!!!
