### ISSUE TITLE
10X input issue after Cell Ranger aggregation

### ISSUE THREAD

**Issue by JBreunig** [aertslab/cisTopic#10]
Getting this error trying to load an aggregation of two samples with the new CellRanger

> > data_folder <- '/media/breunighp/SSD/ssrnaseq/scATAC/Aggr/filtered_peak_bc_matrix/'
> > metrics <- 'singlecell.csv'
> > cisTopicObjectt <- createcisTopicObjectFrom10Xmatrix(data_folder, metrics, project.name = "cisTopicProject")
> Error in dimnamesGets(x, value) : 
 invalid dimnames given for “dgTMatrix” object

I can load it into cisTOPIC by using 10X's recommendation for creating a matrix and going through the workflow that way.

This is the first time I've had an issue with a 10X dataset and I'm wondering if it is due to the aggregation or the new version of CellRanger?

**Comment by cbravo93** [comment]
Hi @JBreunig !

It should be solved now, thanks for noticing :)!
