### ISSUE TITLE
ComplexHeatmap argument cluster_columns  in cellTopicHeatmap

### ISSUE THREAD

**Issue by arutik** [aertslab/cisTopic#11]
Hi,

I'm having this issue when plotting the heatmap with cellTopicHeatmap (as in [this](https://rawcdn.githack.com/aertslab/cisTopic/f628c6f60918511ba0fa4a85366ebf52db5940f7/vignettes/CompleteAnalysis.html) tutorial):
Code: 
cellTopicHeatmap(cisTopicObject, method='Probability', colorBy=c('celltype', 'TREATMENT'), cluster_rows = FALSE, cluster_columns = FALSE)
Error message:
Error in ComplexHeatmap::Heatmap(data.matrix(topic.mat), col = colorPal(20),  :
 formal argument "cluster_columns" matched by multiple actual arguments

My suspicion is that the argument cluster_columns is forced to TRUE, which for me is an issue since I would prefer to group columns according to their status is either treatment or celltype and not be clustered.

Thank you.

**Comment by arutik** [comment]
Also just in general it would be great if after running models and selecting the best one it was possible to refer to the 'topic contribution per cell' heatmap data in the form of a table so that it's easy to customise the plotting, i. e. have something like this - aggregated data for each cell - z-score and/or probability for each topic for this cell and also parameters of this cell from the annotation (sorry my attempt of a table looks a bit crooked here):

cells   |    z_Topic_1   |  z_Topic_2   |   ....   |  z_Topic_n     |     celltype    |  ...(other annotation)...  |   batch
cell_1  |     0.02        |      0.03     |     ....    |       0.01        |      epithelial    |       ..........................      |      01
cell_2     |    0.01       |       0.06      |    ....         |  0.09       |        T-cell      |        ..........................     |        01
...........


I may not be seeing how to do it now, but if it's possible, let me know please

**Comment by cbravo93** [comment]
Hi @arutik!

Indeed, that function clusters the cells using euclidian distances and ward clustering based on the topic-cell matrix you select. If you want to use any other type of clustering (or other analyses out of the pipeline), I would suggest to extract the topic-cell matrix as you say in your second comment so you can customise your plotting better. You can do this with the modelMatSelection function:

```r
TCmatrix <- modelMatSelection(cisTopicObject, target='cell', method='Probability') # You can also extract the region-topic matrix with target='region'
TCmatrix <- t(TCmatrix)
TCmatrix <- cbind(TCmatrix, cisTopicObject@cell.data)) #You can add any annotation you need here, this is for getting the format of your table
```

Hope this helps, let me know if there is something else!

C

**Comment by arutik** [comment]
Thank you so much! This helps a lot 👍 

Actually I see now that this was on the documentation page so sorry for not noticing, however your comments are useful!
