### ISSUE TITLE
Chip-seq files for topic annotation & UCSC-style bams not working

### ISSUE THREAD

**Issue by arutik** [aertslab/cisTopic#12]
Hi @cbravo93, 

1) Not so much about the library, but about the analysis itself: to give the topics meaning, in the [tutorial](https://rawcdn.githack.com/aertslab/cisTopic/f628c6f60918511ba0fa4a85366ebf52db5940f7/vignettes/CompleteAnalysis.html) you used 3 Chip-seq peak files from (I assume) separate bulk Chip-seq experiments. Are there any publicly available Chip-seq files for a range of transcription factors that you would recommend?

2) Getting to the later stages of the tutorial mentioned above, I realised my bam files were not UCSC-style (chromosomes were named 1,2,3,... instead of chr1,chr2,chr3,...) - I fixed that and now have new bam files, but I can't read them and create a cisTopicObject
Some relevant info: Before it used to work with the same code but just non-UCSC bams and
I also made the aggregate pseudo-bulk UCSC-style for this

Code: 
pathToBams <- '/blabla/picard_bam_files_UCSC_style_test/'
bamFiles <- paste(pathToBams, list.files(pathToBams), sep='')
regions <- '/blabla/UCSC_style_peak_aggregated_scATAC_individual.narrowPeak'
cisTopicObject <- createcisTopicObjectFromBAM(bamFiles, regions, project.name='bla')

ERROR: invalid parameter: '/blabla/picard_bam_files_UCSC_style_test/sample_1.bam'
Error in Rsubread::featureCounts(bamfiles, annot.ext = regions_frame,  : 
  No counts were generated.

(while trying to fix this I also run this (Vignette packages):

source("https://bioconductor.org/biocLite.R")
biocLite(c('Rsubread', 'umap', 'Rtsne', 'ComplexHeatmap', 'fastcluster', 'data.table', 'rGREAT', 'ChIPseeker', 'TxDb.Hsapiens.UCSC.hg19.knownGene', 'org.Hs.eg.db'))

but that didn't help)

I'd be happy if you could help.

Thanks

**Comment by arutik** [comment]
Sorry, the second issue seems to be caused by the way I make my bams UCSC-like, so ignore it please.

**Comment by cbravo93** [comment]
Hi @arutik!

Regards the first point, that would depend on which system you are working on (organism/tissue/cell type). Together with ChIP-seq, other assays such as bulk ATAC-seq or DNAse (of e.g. FACS sorted cell types of your population, see the 10X tutorials) can be useful. 

Apart for searching in literature/GEO, there are some ChIP-seq/bulk ATAC/DNAse/H2K27ac/... databases that you could use, such as http://cistrome.org/db/#/ (for mouse and human only), https://chip-atlas.org or https://www.encodeproject.org. 

Hope this is useful!

C

**Comment by arutik** [comment]
Thank you so much!

Re issue 2 for other sufferers: make the regions file (pseudo bulk) UCSC-style and the rest of the functions will work.
