### ISSUE TITLE
Bulk Atac narrowpeak files from Corces 2016

### ISSUE THREAD

**Issue by jk86754** [aertslab/cisTopic#13]
Hi,

Would you guys mind sharing how to easily obtain the bulk ATAC narrowpeak files used in the PBMC tutorial as reference for enrichment testing (Corces et al. 2016 Nat Genet)?

Thanks,

Joe

**Comment by jk86754** [comment]
Also, is there an mm10 version of a similar mouse dataset?

**Comment by cbravo93** [comment]
Hi @jk86754!

The peaks as used in the tutorial can be retrieved from [here](https://drive.google.com/drive/u/1/folders/1AtU4D64SrG1ctlvrDunYFp7qv78UYnHb). Regards on whether there is a similar mouse dataset, I am not sure if there is bulk ATAC for them (I do not work a lot with this system); you can check the resources mentioned in #12 . Also, in the sciATAC-seq Mouse Cell Atlas data from [Cusanovich  and Hill et al., 2018](http://atlas.gs.washington.edu/mouse-atac/data/) you can find accessibility signatures from some of these cell types.

Let me know if you need more information!

C

**Comment by jk86754** [comment]
Thank you for the info!
