### ISSUE TITLE
getCistromeEnrichment parallel computing issues

### ISSUE THREAD

**Issue by jk86754** [aertslab/cisTopic#16]
Hi,

I am getting an error in the 5k PBMC tutorial with the line below:

> cisTopicObject <- getCistromeEnrichment(cisTopicObject, topic=1, TFname='SPI1', aucellRankings = aucellRankings, 
+                                         aucMaxRank = 0.05*nrow(aucellRankings), plot=FALSE)
Using 0 cores.
Error in mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  : 
  'mc.cores' must be >= 1

I tried a couple of possible solutions to this but could not get it to work.

Suggestions would be appreciated!

Thank you!

**Comment by cbravo93** [comment]
Does it work if you run this before?:

```r
 options(mc.cores = 1)
```

or directly specify nCores=1 as argument?

**Comment by jk86754** [comment]
Tried both and got the same error, unfortunately.

**Comment by cbravo93** [comment]
Does this example from AUCell run in your machine: https://github.com/aertslab/AUCell/blob/master/inst/examples/example_AUCell_calcAUC.R ?

**Comment by jk86754** [comment]
yes, the example runs fine.

**Comment by jk86754** [comment]
The only warning i get is 

Warning in .AUCell_calcAUC(geneSets = geneSets, rankings = rankings, nCores = nCores,  :
  Using only the first 5 genes (aucMaxRank) to calculate the AUC.

**Comment by cbravo93** [comment]
That is strange, because the only step where parallelisation is used within the function is for AUCell... Can you try running the function line by line and post the error?

**Comment by cbravo93** [comment]
Ok, I was able to replicate the error! Do you actually have SPI1 enriched in topic 1? I only get this error when I put a TFname for which there is no cistrome in the topic. The number of the topics can vary between runs. I will fix the function to show a warning in this case, thanks!

**Comment by jk86754** [comment]
this indeed resolved the issue. Thank you for your help.
