### ISSUE TITLE
add release tag

### ISSUE THREAD

**Issue by olea-digitalis** [aertslab/cisTopic#18]
I'm experiencing a lot of issues with installing the dependencies for this package from Bioconductor and CRAN, so I would like to make a conda package for it.

According to [this GitHub issue](https://github.com/conda/conda/issues/6674), that can only be done if the repository has a release tag. Could you please add one?

**Comment by cbravo93** [comment]
Hi @Granoia!

The tag is added now. Let me know if you have further problems!

C
