### ISSUE TITLE
Region score question

### ISSUE THREAD

**Issue by thouis** [aertslab/cisTopic#19]
Hello,

First of all, thanks for publishing this work.  It's really useful code and very helpful.

I was wondering about this line:
https://github.com/aertslab/cisTopic/blob/cfcf5099bcde85f37c89ee8b5953732f606171ae/R/PlotCells.R#L316

This looks a little different from what's in the Methods section of the paper, which has the sum of the logarithms in denominator.

I also wondered if there was an explanation available for how to interpret region scores, perhaps a reference where this score is introduced?  I haven't seen it before.

Thanks again.

**Comment by cbravo93** [comment]
Hi @thouis !

There is indeed an error in the formula in the paper and it should be, as written in the code:

![image](https://user-images.githubusercontent.com/19205518/61291101-c95d9b00-a7cd-11e9-89be-c835b55560a2.png)

Thanks a lot for noticing this error, we will contact the editor to correct it in the paper. 

The region scores indicate the importance of each region to each topic (each region will have a score in each topic) and are used in different steps. They are calculated with getRegionsScores() and stored in cisTopicObject@region.data. We use them directly when using AUCell for checking the enrichment of epigenomic signatures (regions are ranked based on this score, in signaturesHeatmap()), and for the dimensionality reduction (where by default we only use the binarised regions). For the rest of the steps (e.g. GREAT, cisTarget) we binarise the topics taking the top regions based on these scores (with binarizecisTopics()), and use this 'top set'. I will go over the documentation to try to make this clearer.

Hope this helps, let me know if there are more questions!

C

**Comment by thouis** [comment]
Thanks for the clarification.  Is this metric from the LDA literature?  I have a general sense how it works, but not a very good one, yet.

**Comment by cbravo93** [comment]
Hi,

This metric specifically is also used in the R package lda for ordering words within topics: https://github.com/slycoder/R-lda/blob/master/R/top.topic.words.R . 

Cheers,

C
