### ISSUE TITLE
plotFeatures and cellTopicHeatmap errors

### ISSUE THREAD

**Issue by jk86754** [aertslab/cisTopic#21]
Hi,

Sorry, one more issue to open. Once again, following the 10x vignette. 
>plotFeatures(cisTopicObject_d0, method='tSNE', target='cell', topic_contr=NULL, colorBy=c('nCounts', 'nAcc','densityClust', 'graphBasedClusters_CRA'), cex.legend = 0.8, 
             factor.max=.75, dim=2, legend=TRUE, col.low='darkgreen', col.mid='yellow', col.high='brown1', intervals=10)
Error in plotFeatures(cisTopicObject_d0, method = "tSNE", target = "cell",  : 
  The variable graphBasedClusters_CRA is not included in the cell data. Please check and re-run.

This is strange because i did run 

>graphBasedClusters_CRA_d0 <- read.table(pathTographBasedClusters_CRA_d0, sep=',', header=TRUE, row.names = 1)
>colnames(graphBasedClusters_CRA_d0) <- 'graphBasedClusters_CRA'
>graphBasedClusters_CRA_d0[,1] <- as.factor(graphBasedClusters_CRA_d0[,1])
>cisTopicObject_d0 <- addCellMetadata(cisTopicObject_d0, graphBasedClusters_CRA_d0)

which all ran just fine. Ideas would be appreciated.

Also, 
> cellTopicHeatmap(cisTopicObject_d0, method='Probability', colorBy=c('densityClust')
Error in ComplexHeatmap::HeatmapAnnotation(df = object.cell.data[, colorBy,  : 
  elements in `col` should be named vectors.

>cisTopicObject_d0 <- addCellMetadata(cisTopicObject_d0, densityClust_d0)
ran without issues for this object.

Thank you,

Joe

**Comment by cbravo93** [comment]
Hi,

Can you check colnames(cisTopicObject_d0@cell.data)? 

Cheers,

C

**Comment by jk86754** [comment]
There is indeed no 'graphBasedClusters_CRA' in the colnames.


> colnames(cisTopicObject_d0@cell.data)
 [1] "nCounts"                              "nAcc"                                 "10X_total"                            "10X_duplicate"                       
 [5] "10X_chimeric"                         "10X_unmapped"                         "10X_lowmapq"                          "10X_mitochondrial"                   
 [9] "10X_passed_filters"                   "10X_cell_id"                          "10X_is__cell_barcode"                 "10X_TSS_fragments"                   
[13] "10X_DNase_sensitive_region_fragments" "10X_enhancer_region_fragments"        "10X_promoter_region_fragments"        "10X_on_target_fragments"             
[17] "10X_blacklist_region_fragments"       "10X_peak_region_fragments"            "densityClust"

I re-ran 
>cisTopicObject_d0 <- addCellMetadata(cisTopicObject_d0, graphBasedClusters_CRA_d0)

and now the colname does appear and cellTopicHeatmap works. Not sure why i had to add it again but it does work now :)

Still not sure about cellTopicHeatmap, though...

**Comment by cbravo93** [comment]
Can you check if the densityClust column is a factor?

**Comment by jk86754** [comment]
> is.factor(cisTopicObject_d0@cell.data$densityClust)
[1] TRUE

Thanks,

Joe

**Comment by JBreunig** [comment]
Just to chime in, I had the same problem, having to run "cisTopicObject_d0 <- addCellMetadata(cisTopicObject_d0, graphBasedClusters_CRA_d0)" twice.  

To be fair, I never figured out exactly at which step the metadata got dropped but re-running that command always solved it.

**Comment by cbravo93** [comment]
May it be in this line (on the densityClust part)?

cisTopicObject@cell.data <- cisTopicObject@cell.data[, -ncol(cisTopicObject@cell.data)]

It is not made to be run, I added it for deleting the densityClust column when checking parameters, will take it out. For the error in cellTopicHeatmap, does it also occur when using the precomputed cisTopicObject?

Cheers,

C

**Comment by jk86754** [comment]
Thanks. If i can make densityClust work, cellTopicHeatmap works as well.
