### ISSUE TITLE
selectModel plot when returnType = 'selectedModel' (cisTopic 0.2.1)

### ISSUE THREAD

**Issue by dagarfield** [aertslab/cisTopic#27]
Hi,

This may well be user error, but I'm struggling to locate the likelihoods generated by runModels when returnType = 'selectedModel'. 

#
> cisTopicObject@log.lik
Object of class "data.frame"
data frame with 0 columns and 0 rows
# 

I'd love to be able to create a plot similar to what is generated by default with selectModel, but this only seems to work when returnType has the default value, and it sure would be handy to have for a larger set of tested models.

Thanks!

**Comment by cbravo93** [comment]
Hi @dagarfield !

There was indeed a bug in this option, it was not correctly updated after the changes from v1 to v2. I just pushed some changes, should be ok now. Thanks a lot for noticing!

Let me know if you have any more issues!

C
