### ISSUE TITLE
Motif Enrichment for mm9

### ISSUE THREAD

**Issue by eliduong** [aertslab/cisTopic#3]
Hi,

I noticed that the cisTarget database only has ranking by regions for hg19.  If my accessibility data is mapped to mm9, is the best option to liftover to hg19 to do motif enrichment analysis?

Thank you!
E

**Comment by eliduong** [comment]
I'm also having trouble downloading the hg19 regions cistarget databases using wget or zcurl.  Both the regions databases can't be found but no issues with the gene databases for mouse or human.

**Comment by cbravo93** [comment]
Hi, 

The human database (version 8, hg19-regions-9species.all_regions.mc8nr) should be accessible now. Regards the first question, you should use the mm9 database. Unfortunately, we are having storage issues at the moment; but the mm9 database should be accessible next week.

Cheers!

**Comment by eliduong** [comment]
That'd be great!  I'll check in next week to download.  Thanks and happy new year!

**Comment by cbravo93** [comment]
Until then, you can upload the topic bed files in the web version of cisTarget for motif enrichment (select mm9): https://gbiomed.kuleuven.be/apps/lcb/i-cisTarget-mcv8/index.php . I'll try to solve it as soon as possible, happy new year :)!

**Comment by eliduong** [comment]
Hi, any updates on uploading the mm9 database?  Thank you!

**Comment by cbravo93** [comment]
Hi Eli,

Unfourtunately, we are still trying to make the data accessible from its new location; however, we are waiting for external steps to be done (few left). I hope it will be solved very soon!

Cheers!

**Comment by eliduong** [comment]
Thanks for the update!

**Comment by cbravo93** [comment]
Hi Eli,

After solving additional hardware problems, we have managed to upload the region-based databases. You can find the mm9 database at: 
https://resources.aertslab.org/cistarget/databases/mus_musculus/mm9/refseq_r70/mc9nr/region_based/mm9-regions-9species.all_regions.mc9nr.feather . 

Sorry for the delay and hope everything works fine!
