### ISSUE TITLE
Arabidopsis genome

### ISSUE THREAD

**Issue by cuperusj** [aertslab/cisTopic#30]
Working on Arabidopsis, which is anot a USCS supported genome, any ideas on how to deal with getting this info:

txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene

getBigwigFiles(cisTopicObject, path='output/cisTopics_asBW', seqlengths=seqlengths(txdb))

and other areas that need genome annotation info

**Comment by cbravo93** [comment]
Hi @cuperusj !

You can switch the txdb to TxDb.Athaliana.BioMart.plantsmart28. If you have problems with the chromosome names, you may need to change the seqlevels (see [here](https://support.bioconductor.org/p/70715/)).

I hope this helps!
