### ISSUE TITLE
Grouping regions into topics

### ISSUE THREAD

**Issue by arutik** [aertslab/cisTopic#32]
Hi @cbravo93 !

Had a conceptual question: having read the paper I still struggle to understand how the algorithm groups regions into topics? Based on what? Is it based on co-occurence? Similar patterns of other regions? Basically how can you interpret this relationship?

Thank you.

**Comment by cbravo93** [comment]
Hi @arutik!

Regions are clustered based on co-ocurrence across the data set.

Cheers!

C
