### ISSUE TITLE
error in cisTopic(logLikelihoodByIter)

### ISSUE THREAD

**Issue by Sububioinfo** [aertslab/cisTopic#35]
Hi,
I am using the following tutorial, in step 24 am getting the following error. i got the same data until step 23, there is no problem in that. please try to help me. am using R3.5.1 and checked with R.3.6.1 also, and got the same error message
https://nbviewer.jupyter.org/github/pinellolab/scATAC-benchmarking/blob/master/Real_Data/Buenrostro_2018/run_methods/cisTopic/cisTopic_buenrostro2018.ipynb?flush_cache=true

step 24
logLikelihoodByIter(cisTopicObject, select=c(10, 20, 25, 30, 35, 40))

error
Error in scales::hue_pal(l = 60:100) : length(l) == 1 is not TRUE
Calls: logLikelihoodByIter ... unique -> col2rgb -> %in% -> <Anonymous> -> stopifnot

**Comment by JBreunig** [comment]
I'm getting this error as well and hadn't in the past.  I also get the same error at this step:

plotFeatures(cisTopicObject, method='tSNE', target='cell', topic_contr=NULL, colorBy=c('nCounts', 'nAcc','densityClust', 'graphBasedClusters_CRA'), cex.legend = 0.8, factor.max=.75, dim=2, legend=TRUE, col.low='darkgreen', col.mid='yellow', col.high='brown1', intervals=10)

**Comment by Sububioinfo** [comment]
Hi JBreunig,
Did you rectified the problem. do you have any solution

**Comment by JBreunig** [comment]
No, I haven't figured it out.  I haven't had this problem in the past with cisTopic, so it's likely due to version changes between cisTopic and the scales package.

**Comment by cbravo93** [comment]
Hi!

Sorry for the delay! As @JBreunig said, it was due to an update in the scales package. I fixed the color function, it should work now if you reinstall.

Thanks for noticing!

C

**Comment by Sububioinfo** [comment]
Thanks for updating, now its working.
