### ISSUE TITLE
Export the topic-signature matrix

### ISSUE THREAD

**Issue by arutik** [aertslab/cisTopic#36]
Hi @cbravo93 ,

Is it possible to export the topic-signature matrix similar to how modelMatSelection exports either topic-cell or topic-region matrices?

Thank you.

Sincerely,
Anna Arutyunyan

**Comment by cbravo93** [comment]
Hi @arutik !

I have just added topicSignaturesMatrix() for this purpose.

Cheers!

C

**Comment by arutik** [comment]
Thanks a lot!!
