### ISSUE TITLE
How to load multiple 10X runs to cisTopic? 

### ISSUE THREAD

**Issue by cartal** [aertslab/cisTopic#39]
Hi, 

I was wondering if you have a propose way to analyse multiple 10X runs at once. I'm not very familiar with the R data structure that `cisTopic` uses; however, it would be good to have something like an equivalent of `concatenate` function from `anndata`. 

Any suggestions? :)

**Comment by cbravo93** [comment]
Hi @cartal !

You can take a look to [cellranger-atac aggr](https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/using/aggr) to aggregate runs. Directly from cisTopic, you can create independent objects per run and then create a combined object:

```r
# Create object for the first run
pathTo10X <- '/Run_1/'
fragments <- paste0(pathTo10X, 'fragments.tsv.gz')
regions <-  paste0(pathTo10X, 'peaks.bed')
metrics <- paste0(pathTo10X, 'singlecell.csv')
cisTopicObject1 <- createcisTopicObjectFrom10X(fragments, regions, metrics, project.name='Run_1', min.cells=0)
# We set min.cells=0 to keep all rows (regions). When combined, regions that are not accessible in any cell in any 
# of the runs will be taken out.

# Add _1 to cell names from run 1
cell.names <- cisTopicObject1@cell.names
new.cell.names <- paste0(cell.names, '_1')
cisTopicObject1 <- renameCells(cisTopicObject1, new.cell.names)

# Create object for the second run
pathTo10X <- '/Run_2/'
fragments <- paste0(pathTo10X, 'fragments.tsv.gz')
regions <-  paste0(pathTo10X, 'peaks.bed')
metrics <- paste0(pathTo10X, 'singlecell.csv')
cisTopicObject2 <- createcisTopicObjectFrom10X(fragments, regions, metrics, project.name='Run_2', min.cells=0)

# Add _2 to cell names from run 2
cell.names <- cisTopicObject2@cell.names
new.cell.names <- paste0(cell.names, '_2')
cisTopicObject2 <- renameCells(cisTopicObject2, new.cell.names)

# Combine data 

count.matrix <- cbind(cisTopicObject1@count.matrix, cisTopicObject2@count.matrix)
cell.data <- rbind(cisTopicObject1@cell.data, cisTopicObject2@cell.data)
region.data <- cbind(cisTopicObject1@region.data, cisTopicObject2@region.data) 

# Create combined cisTopicObject
cisTopicObjectCombined <- createcisTopicObject(count.matrix, project.name='Combined')
cisTopicObjectCombined <- addCellMetadata(cisTopicObjectCombined, cell.data)
cisTopicObjectCombined <- addRegionMetadata(cisTopicObjectCombined, region.data)
```

I hope this is useful, let me know if you have further questions :)

Cheers,

C

**Comment by ktpolanski** [comment]
Here's that same code snippet, but generalised into a for loop for easy loading of multiple samples. Needs to have `samples` set, and `pathTo10X` depend on the within-loop `sample`. Just leaving it here for posterity. Some sort of merging function would be nice eventually.

	library(rlist)

	count.matrix = list()
	cell.data = list()
	region.data = list()

	samples = 
	for (sample in samples)
	{
		pathTo10X = 
		fragments = paste0(pathTo10X, 'fragments.tsv.gz')
		regions =  paste0(pathTo10X, 'peaks.bed')
		metrics = paste0(pathTo10X, 'singlecell.csv')
		cisTopicObject = createcisTopicObjectFrom10X(fragments, regions, metrics, project.name=sample, min.cells=0)
	
		# Add sample name to cell names
		cell.names = cisTopicObject@cell.names
		new.cell.names = paste0(sample, '_', cell.names)
		cisTopicObject = renameCells(cisTopicObject, new.cell.names)
	
		# Store parts of object for collapsing later
		count.matrix[[sample]] = cisTopicObject@count.matrix
		cell.data[[sample]] = cisTopicObject@cell.data
		region.data[[sample]] = cisTopicObject@region.data
	}

	# Combine data 
	count.matrix = list.cbind(count.matrix)
	cell.data = list.rbind(cell.data)
	region.data = list.cbind(region.data) 

	# Create combined cisTopicObject
	cisTopicObjectCombined = createcisTopicObject(count.matrix, project.name='Combined')
	cisTopicObjectCombined = addCellMetadata(cisTopicObjectCombined, cell.data)
	cisTopicObjectCombined = addRegionMetadata(cisTopicObjectCombined, region.data)
