### ISSUE TITLE
Downloading .feather file

### ISSUE THREAD

**Issue by jf292** [aertslab/cisTopic#41]
Unfortunately not able to access and download the 'hg19-regions-9species.all_regions.mc8nr.feather' from 'https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc8nr/region_based/' . Could you please direct me to alternate source or let me know when this would be made available? 

Thanks,
Praveen

**Comment by cbravo93** [comment]
Hi @jf292 !

We had a few problems with our servers last week, but now it is back to normal. You can find it at https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc9nr/region_based/hg19-regions-9species.all_regions.mc9nr.feather (for v9) or https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc8nr/region_based/hg19-regions-9species.all_regions.mc8nr.feather (for v8). The main difference is the amount of motifs (20K for v8, 24K for v9)

I hope this is useful!

C

**Comment by wjyzidane** [comment]
I am reading the [Basic tutorial on simulated single cell epigenomes from melanoma cell lines V3] and can not find pathToFeather <- "/feather/hg19-regions-9species.all_regions.mc9nr.feather" in this link(https://drive.google.com/drive/folders/18ETGIKgXkILo3Xfv9KuysOMqchmSfFX2?usp=sharing).

The link provided above is also invalid.
