### ISSUE TITLE
Undefined functions

### ISSUE THREAD

**Issue by wkopp** [aertslab/cisTopic#43]
Hi,

it seems that several functions are currently not defined in the package, including `runModels` and `runWrapLDAModels`.

Best,
Wolfgang

**Comment by cbravo93** [comment]
Hi @wkopp !

runModels is now runCGSModels, and the WarpLDA function is runWarpLDAModels (instead of Wrap). Are there more functions?

Thanks for reporting!

C

**Comment by wkopp** [comment]
Thank you for the clarification.
