### ISSUE TITLE
Installation Trouble from cisTopic/R/RunModels.R

### ISSUE THREAD

**Issue by Toseph** [aertslab/cisTopic#46]
I have installed all the dependencies cisTopic requires on R-3.5.2, but while trying to install the package from devtools or source I keep hitting this error on line 261 from an equal-sign operator. 

Unsure if this is due to a change in the code-base causing some syntactical error on R. 

`> devtools::install_github("aertslab/cisTopic")
Downloading GitHub repo aertslab/cisTopic@master
Skipping 1 packages not available: text2vec
✔  checking for file ‘/tmp/Rtmp5FkfaK/remotese17e72b625e9/aertslab-cisTopic-3e3cd00/DESCRIPTION’ ...
─  preparing ‘cisTopic’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘cisTopic_0.3.0.tar.gz’ (6.3s)

Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘cisTopic’ ...
** R
Error in parse(outFile) :
  /tmp/RtmpXwCkm6/R.INSTALLe1e87f993a10/cisTopic/R/RunModels.R:261:33: unexpected '='
260:
261:   if (length(models) < 3 && type=
                                     ^
ERROR: unable to collate and parse R files for package ‘cisTopic’
* removing ‘/usr/lib64/R/library/cisTopic’`

**Comment by Toseph** [comment]
To get around the two "type=" errors, I changed the lines on 261 and 265 to "==" which allows cisTools to finish compile and installing on R from source, though it might have been incorrect to do so this way. 

`[root@rstudio-sanjana01 snapatac]# R CMD INSTALL cisTopic
installing to library ‘/usr/lib64/R/library’
installing *source* package ‘cisTopic’ ...
R
Error in parse(outFile) :
  /root/snapatac/cisTopic/R/RunModels.R:261:33: unexpected '='
260:
261:   if (length(models) < 3 && type=`

`Error in parse(outFile) :
  /root/snapatac/cisTopic/R/RunModels.R:265:61: unexpected '='
264:
265:   if (is.null(object@calc.params[['runWarpModels']]) && type=`

Now when loading the library it loads but with warnings, 

` > library(cisTopic)
There were 17 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: replacing previous import ‘GenomicRanges::shift’ by ‘data.table::shift’ when loading ‘cisTopic’
2: replacing previous import ‘data.table::last’ by ‘dplyr::last’ when loading ‘cisTopic’
3: replacing previous import ‘GenomicRanges::union’ by ‘dplyr::union’ when loading ‘cisTopic’
4: replacing previous import ‘GenomicRanges::intersect’ by ‘dplyr::intersect’ when loading ‘cisTopic’
5: replacing previous import ‘GenomicRanges::setdiff’ by ‘dplyr::setdiff’ when loading ‘cisTopic’
6: replacing previous import ‘data.table::first’ by ‘dplyr::first’ when loading ‘cisTopic’
7: replacing previous import ‘data.table::between’ by ‘dplyr::between’ when loading ‘cisTopic’
8: replacing previous import ‘dplyr::failwith’ by ‘plyr::failwith’ when loading ‘cisTopic’
9: replacing previous import ‘dplyr::id’ by ‘plyr::id’ when loading ‘cisTopic’
10: replacing previous import ‘dplyr::summarize’ by ‘plyr::summarize’ when loading ‘cisTopic’
11: replacing previous import ‘dplyr::count’ by ‘plyr::count’ when loading ‘cisTopic’
12: replacing previous import ‘dplyr::desc’ by ‘plyr::desc’ when loading ‘cisTopic’
13: replacing previous import ‘dplyr::mutate’ by ‘plyr::mutate’ when loading ‘cisTopic’
14: replacing previous import ‘dplyr::arrange’ by ‘plyr::arrange’ when loading ‘cisTopic’
15: replacing previous import ‘dplyr::rename’ by ‘plyr::rename’ when loading ‘cisTopic’
16: replacing previous import ‘dplyr::summarise’ by ‘plyr::summarise’ when loading ‘cisTopic’
17: replacing previous import ‘dplyr::collect’ by ‘text2vec::collect’ when loading ‘cisTopic’
>`

**Comment by cbravo93** [comment]
Hi @Toseph !

Indeed, it was a typo I accidentally added in the last update yesterday, and your solution is correct. Now it should be solved.

Thanks a ton for reporting!

C
