### ISSUE TITLE
getBigwigFiles functions error

### ISSUE THREAD

**Issue by ytang0831** [aertslab/cisTopic#51]
Hi!
I tried to generate BW file after get region scores.

library(TxDb.Mmusculus.UCSC.mm9.knownGene)
txdb<-TxDb.Mmusculus.UCSC.mm9.knownGene
getBigwigFiles(cisTopicObject, path='output/cisTopics_asBW', seqlengths=seqlengths(txdb))

However, I get the error message below:
Error in FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i], X_elt_end[i])),  : 
  BigWig ranges cannot overlap

Looking forward to your Suggestions！

**Comment by cbravo93** [comment]
Hi @ytang0831 !

Do your regions overlap?

C

**Comment by luzgaral** [comment]
Hi @cbravo93 

I'm facing the same issue. Because of the way I call peaks, they may overlap in 1bp. Any suggestion?

Thanks!
