### ISSUE TITLE
Error in metadataFeather(path) 

### ISSUE THREAD

**Issue by sylestiel** [aertslab/cisTopic#55]
<img width="918" alt="Screen Shot 2020-08-27 at 10 45 22 AM" src="https://user-images.githubusercontent.com/64283689/91464774-90a64700-e852-11ea-85a0-12bdbdce364a.png">

Hi,

I'm having difficulty with accessing the regions feather link for subsequent to the lift over from mm10 to mm9.
Need help getting past it.

Thanks!

**Comment by cbravo93** [comment]
Hi @sylestiel !

You need to download the file. Here you have some tips on how to download it: https://resources.aertslab.org/cistarget/help.html

Cheers!

C

**Comment by sylestiel** [comment]
I downloaded to an external drive but my system crashed from want of space. Is there another work around ?
Thanks!
