### ISSUE TITLE
Is aggregation of dataset required for cisTopic

### ISSUE THREAD

**Issue by sylestiel** [aertslab/cisTopic#57]
Hi @cbravo93 

Is it appropriate to run cisTopic on single cell ATAC dataset without aggregation in Cell Ranger?  Alternatively, would you recommend only running it on aggregated datasets?

Thanks!

**Comment by cbravo93** [comment]
Hi @sylestiel 

We have used it with and without aggregation in a couple data sets, results are similar.

Cheers!

C

**Comment by sylestiel** [comment]
Thanks!!!
