### ISSUE TITLE
license

### ISSUE THREAD

**Issue by abotzki** [aertslab/cisTopic#58]
Hi, we are currently annotating VIB KU Leuven tools in bio.tools - do you have a licence you could specify here in the repo?
Thanks.

**Comment by cbravo93** [comment]
Hi @abotzki !

It has GPL-3 license, as mentioned in the [DESCRIPTION file](https://github.com/aertslab/cisTopic/blob/master/DESCRIPTION). Is that what you mean?

Thanks!

C

**Comment by abotzki** [comment]
Hi Carmen, yes, this is what I was looking for. The automatic routines did not pick up the license form the description file. Cheers.
