### ISSUE TITLE
The function runModels is missing

### ISSUE THREAD

**Issue by kridsadakorn** [aertslab/cisTopic#59]
Hi,

The R code of runModels() is missing as well as NAMESPACE. But it is presented in the RD file.
I would like to ask that it was accidentally removed or the function was renamed to something else?

Thank you very much in advance for the answer

**Comment by cbravo93** [comment]
Hi @kridsadakorn!

Nice catch, indeed the runModels.Rd shouldn't be there! The function runModels() was deprecated a while ago, you can se runCGSModels() for modelling based on Collapsed Gibbs Sampling (equivalent to runModels()), or runWarpLDAModels() (for modelling based on WarpLDA).

I removed the runModels.Rd file.

Let me know if you have further issues!

C

**Comment by kridsadakorn** [comment]
Thank you for your reply.  `runCGSModels` does work. :)
