### ISSUE TITLE
10X chromium scATAC matrix input

### ISSUE THREAD

**Issue by JBreunig** [aertslab/cisTopic#6]
Looking forward to trying this impressive package!  Might you have a workflow for inputting 10X Chromium scATAC data?

**Comment by JBreunig** [comment]
Nevermind, I have it working.

**Comment by cbravo93** [comment]
Hi @JBreunig!

I have added a tutorial on the 5k PBMC data set from 10X. Thanks for using cisTopic!

**Comment by JBreunig** [comment]
Great, thank you!
