### ISSUE TITLE
Rsubread should be listed as a required package

### ISSUE THREAD

**Issue by kridsadakorn** [aertslab/cisTopic#60]
Hi,

I would like to suggest that, according to the code below, the package Rsubread should be listed under `import`, and add to the Roxygen part as well. Without `Rsubread`, it causes the code to break during runtime.

```
# Check dependencies
  if(! "Rsubread" %in% installed.packages()){
    if (Sys.info()['sysname'] != 'Windows'){
      stop('Please, install Rsubread: \n source("https://bioconductor.org/biocLite.R") \n biocLite("Rsubread")')
    }
```

Thank you

**Comment by cbravo93** [comment]
Hi @kridsadakorn !

The package Rsubread had some installation issues in Windows, so if putting it as dependency then cisTopic wouldn't be installable at all on Windows. It is only used in that function, so all the rest should run without issues. If working in MacOS/Linux the function should ask you to install Rsubread, and run without issues after the installation. Also I just saw that the latest versions should work in Windowns 10 too, so it should also work installing it and running afterwards (I will update the code). Can you try to install Rsubread and running the function?

In which SO are you working? If it is MacOS/Linux, can you share the error and your sessionInfo()? If you need to run the function but are working on a Windows machine and the Rsubread installation fails I can share some workaround code. 

The function is meant to create the count matrix from single cell bam files (e.g. one file per cell), if you have a single bam file with all cells you can convert it to a fragments file with sinto or bedops and then use the `createcisTopicObjectFrom10X` function.

Let me know what is your case!

C

**Comment by kridsadakorn** [comment]
Thank you for your reply. I installed it separately. I didn't know that `Rsubread` is not compatible with Windows.
