### ISSUE TITLE
cistopic object to archR

### ISSUE THREAD

**Issue by ytang0831** [aertslab/cisTopic#61]
Hi! Thans for your perfect work. I want to know if there any way to convert cistopic object into archR object？ Thanks a lot！

**Comment by cbravo93** [comment]
Hi @ytang0831 !

It is possible to include cell or region metadata and embeddings from cisTopic in an ArchR object, but exporting the rest is not possible to my knowledge (the remaining data in a cisTopicObject depends on the topic modelling modelling results, and the structure of an ArchR object is different).

I hope this is useful,

Carmen
