### ISSUE TITLE
Question about createcisTopicObject

### ISSUE THREAD

**Issue by kridsadakorn** [aertslab/cisTopic#63]
Hi, I would like to ask something about createcisTopicObject

```
count.matrix Count matrix containing cells as rows and regions as columns. The row names must be the coordinates in position format (e.g. chr1:110-610).
```

I wonder whether regions are as columns or rows?
I also wonder whether there is any bug in the code or just the wrong description?

Thank you

**Comment by cbravo93** [comment]
Hi there!

It's a bug in the description, rows should be regions. I will update it shortly.

Thanks for the report!

C
