### ISSUE TITLE
possibility to use BAM files from bulk ChIP

### ISSUE THREAD

**Issue by abedkurdi** [aertslab/cisTopic#65]
Hello Guys,
is it possible to use your tool using BAM files coming from bulk ChIP or it is restricted to single-cell only?
You said in your paper that BAM files should come from single-cell, I am asking for more clarification.

Thanks in advance.

**Comment by cbravo93** [comment]
Hi!

You can use any type of bam file (also bulk), but keep in mind that the topic modelling will not work well if you have very limited samples. If that's the case, you could simulate single cells from your bulks (by sampling reads).

Cheers!

C
