### ISSUE TITLE
input from fragments.tsv.gz?

### ISSUE THREAD

**Issue by JBreunig** [aertslab/cisTopic#68]
I'm trying to examine a published dataset and they provide only the fragments.tsv.gz.  Is there any way to move forward with only this file?
Thanks in advance!
J

**Comment by cbravo93** [comment]
Hi JBreuning!

You can give it a try with `createcisTopicObjectFrom10X`, you will only need to mimic a metrics file as 10x with a column [,'is__cell_barcode'] specifying which barcodes to use.

Cheers!

C
