### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by andrewjkwok** [aertslab/cisTopic#69]
Hi,

Many thanks for the very interesting looking package. I was just trying to install this while working on my cluster but for some reason hit a strange error when trying to install in R4.1:

```
> devtools::install_github("aertslab/cisTopic")
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'NeedsCo ...' is malformed!
```

However, the package successfully installs into R4.0. I couldn't quite find a similar issue hence the new one. Please let me know what else might be helpful to provide.

**Comment by cbravo93** [comment]
I havent been able to reproduce this error, at least in 4.1.1 (Mac).  Does it only occur with this package? Using remotes instead of devtools helps by any chance?

Cheers!

Carmen

**Comment by andrewjkwok** [comment]
It only occurs with this package - and doesn't work with remotes either unfortunately. I've gone back to the R4.0 version but really don't know how to solve the 4.1 installation issue.
