### ISSUE TITLE
mm9 vs. mm10

### ISSUE THREAD

**Issue by JBreunig** [aertslab/cisTopic#7]
The package is very intuitive and provides great insight.

I've noticed that the GREAT function gives an error with mm9 but not with mm10:

> cisTopicObject <- GREAT(cisTopicObject, genome='mm9', fold_enrichment=2, geneHits=1, sign=0.05, request_interval=10)
Error in submitGreatJob(coord, species = genome, request_interval = request_interval,  : 
  GREAT encountered a user error (message from GREAT web server)

Will I run into issues switching back and forth between mm9 and mm10 in the workflow as the feather file is mm9?  i.e. can I run the other analysis with mm10 up until GREAT and then switch to mm9 for TF motif enrichment and formation of cistromes?

Alternatively, is there any reason why GREAT isn't accepting the above command with mm9 that can be fixed?

**Comment by cbravo93** [comment]
Hi @JBreunig !

Regards rGREAT, I am only able to reproduce this error when my regions are in mm10 but I select mm9 as genome (or vice versa). Which one is the genome assembly of your data, mm9 or mm10? If it is mm10, this code should work:

```r
cisTopicObject <- GREAT(cisTopicObject, genome='mm10', fold_enrichment=2, geneHits=1, sign=0.05, request_interval=10)
pathToFeather <- '/media/data/lcb/icistarget/data/rankings/feather/mm9-DHS_enh_prom_pennstate-9species.all_regions.mc9nr.feather' 
library(R.utils)
url <- "http://hgdownload.soe.ucsc.edu/goldenPath/mm10/liftOver/mm10ToMm9.over.chain.gz"
mm10Tomm9.chain <- "mm10Tomm9.over.chain"
download.file(url, destfile = paste0(mm10Tomm9.chain, ".gz"))
gunzip(paste0(mm10Tomm9.chain, ".gz"))
mm10Tomm9.chain  <- import.chain(mm10Tomm9.chain)

# Obtain liftOver dictionary (as list)
mm10_coord <- cisTopicObject@region.ranges
mm10_to_mm9_list <- liftOver(mm10_coord, mm10Tomm9.chain)

cisTopicObject <- binarizedcisTopicsToCtx(cisTopicObject, liftOver=mm10_to_mm9_list, genome='mm9')
cisTopicObject <- scoredRegionsToCtx(cisTopicObject, liftOver=mm10_to_mm9_list, genome='mm9')
cisTopicObject <- topicsRcisTarget(cisTopicObject, genome='mm9', pathToFeather, reduced_database=FALSE, nesThreshold=3, rocthr=0.005, maxRank=20000, nCores=4)
cisTopicObject<- getCistromes(cisTopicObject, annotation = 'Both', nCores=5)
```

Let me know if this is not the case!

C

**Comment by JBreunig** [comment]
This is almost certainly my issue as we used mm10.  Thanks for the code and help solving it.

**Comment by JBreunig** [comment]
Hi Carmen,
Your liftover code worked fine.  However, I'm running out of  memory at the topicsRcisTarget line:

> cisTopicObject <- topicsRcisTarget(cisTopicObject, genome='mm9', pathToFeather, reduced_database=FALSE, nesThreshold=3, rocthr=0.005, maxRank=20000, nCores=4)

(Running Ubuntu 18.04 on a dual Xeon workstation with 128Gb of ram and a 32 gb swapdisk.)  Memory use starts at 8GB of RAM after running the command but slowly grows until it uses both RAM and swapdisk and then creates an error.  This is a dataset of 2,695 mouse tumor cells.

Initial settings:
>   cisTopicObject <- runModels(cisTopicObject, topic=c(20), seed=987, nCores=14, burnin = 200, iterations = 250, returnType = "selectedModel", addModels=FALSE)

> cisTopicObject <- selectModel(cisTopicObject, select=20)

I should add that I've had issues with corrupted feather databases with SCENIC but it doesn't look like I can checksum the mouse feather file mm9-regions-9species.all_regions.mc9nr.feather with the sha256sum.txt file.  (It takes 5 days to download each feather file.)

Any suggestions?  Thanks in advance!
Josh

**Comment by cbravo93** [comment]
Hi @JBreunig !

Can you try reducing the number of cores?

Cheers!

C

**Comment by JBreunig** [comment]
Reducing the cores worked...thanks!
Best,
J
