### ISSUE TITLE
Tutorial Dataset files

### ISSUE THREAD

**Issue by AAA-3** [aertslab/cisTopic#70]
Hello everyone! 

I am going through the Version three tutorial.

I think the provided data from the exercise is missing some files - if I have misunderstood please let me know! 

To navigate this issue, I instead tried to load in the RDS files into R and received this error:

```
Error in load("/home/ali/Dokumente/RPractise/cisTopic/WarpLDA_cisTopicObject_pbmc.Rds") : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning messages:
1: In readChar(con, 5L, useBytes = TRUE) :
  truncating string with embedded nuls
2: file ‘WarpLDA_cisTopicObject_pbmc.Rds’ has magic number 'X'
  Use of save versions prior to 2 is deprecated 

```

And idea how to proceed? Alternatively, if soeone could supply me with the exact raw files used for the tutorial I could proceed with those - checkign hte 10X genomics sight revealed multiple "5K PBMC from healthy donor datasets".

Any help would be appreciated - I want to use this cool software for some of my ATAC seq data.

Thanks in advance!

**Comment by cbravo93** [comment]
Hi!

You should use readRDS instead of load.

Cheers!

C
