### ISSUE TITLE
tSNE Clustering Thresholds

### ISSUE THREAD

**Issue by AAA-3** [aertslab/cisTopic#71]
Hello everyone,

This is not an issue with the program but rather a discussion topic to help me understand the following: 

The vignette has a section in Part A which dimensionally reduced the LDA distributions into a tsne with two optionss (runtSNE and Rtsne). 

This is followed by creating a graph to check thresholds. I want to know if:

1. What are these thresholds for? 
2. Why are the red clusters important?

![image](https://user-images.githubusercontent.com/68068335/166911388-bed2f112-78f6-452d-98b5-934496d61a97.png)

**Comment by cbravo93** [comment]
This is the density peak clustering algorithm used by Monocle 2 as in: https://www.nature.com/articles/nature25981#Sec2 . You can find more information in the Monocle 2 paper: https://www.nature.com/articles/nmeth.4402 and in the original algorithm paper: https://www.science.org/doi/10.1126/science.1242072

Cheers!

C
