### ISSUE TITLE
How can I run cisTopic in R 4.0

### ISSUE THREAD

**Issue by Paul-YPH** [aertslab/cisTopic#73]
I installed cisTopic in R 4.0 successfully, but it seems that the tool can't run successfully. I've been stuck in `runCGSModels` for a long time. It keeps saying it's `Running models...'` but I can't get any results.

**Comment by cbravo93** [comment]
Hi!

Can you give it a try with the example data or check with `htop` if it is running? It can take a while to run, it can be it is just running.

C

**Comment by Paul-YPH** [comment]
Thank you for your reply. It did take a long time to run.
