### ISSUE TITLE
Ununsed Arguement error in cisTopic/TcisTarget

### ISSUE THREAD

**Issue by AAA-3** [aertslab/cisTopic#74]
Running Code:

```
date()
pathToFeather <- "/home/ali/Downloads/hg19-regions-9species.all_regions.mc9nr.feather" #deleted after tutorial. file vv large
cisTopicObject <- topicsRcisTarget(object=cisTopicObject, genome='hg19', pathToDb=pathToFeather, reduced_database=FALSE, nesThreshold=3, rocthr=0.005, maxRank=20000)#, nCores=5)
date()
```

Produces error:
```
Loading required package: RcisTarget
Error in cisTarget(topicsList[[i]], motifRankings, motifAnnot = motifAnnot,  : 
  unused argument (geneErnMmaxRank = maxRank)
```

I think there is something wrong with how cisTopic is calling RcisTarget. cisTarget looks for `geneErnMaxRank` not `geneErnMmaxRank`.

Is there a way to fix this? I have copied this code directly from the melanoma vignette.

**Comment by cbravo93** [comment]
Hi!

Yeah I fixed it (we updated the name in RcisTarget but not here a few weeks back), you can reinstall it and try again :)

Thanks!
