### ISSUE TITLE
add cisTopic output to Seurat object?

### ISSUE THREAD

**Issue by klgoss** [aertslab/cisTopic#77]
Hello, thanks for creating this tool! I have a large 10x multiome dataset and want to use Seurat to preprocess the RNA data and cisTopic to preprocess the ATAC (I plan to run SCENIC+ later on). However, I want to use Seurat to create a WNN graph and assign cell types from those clusters. Is there a way to add the cisTopic output into my Seurat object so that I can use the ATAC data preprocessed with cisTopic instead of having to preprocess it with Seurat? I am trying to stay as consistent as possible. Thanks for any insight!!

**Comment by cbravo93** [comment]
Hi @klgoss !

cisTopic is deprecated, you will have to move to https://github.com/aertslab/pycisTopic. You can process your data with Seurat if you want, the only thing you will need for pycisTopic/SCENIC+ from it is: 1) a table with barcodes/cell names and corresponding cell type and 2) the gene expression matrix.

Cheers,

C
