### ISSUE TITLE
Running Cistopic

### ISSUE THREAD

**Issue by Sayyam-Shah** [aertslab/cisTopic#78]
Hello @cbravo93,

I am interested in using cistopic, however, I am experiencing some problems as I am more used to RNA seq data.
I am creating the cistopic object below.
matrix <- BM77@assays$ATAC@counts
rownames(matrix) <- sub('-', ':', rownames(matrix))
cisTopicObject <- createcisTopicObject(count.matrix = matrix)

However, I get an error upon running the runWarpLDAModels method.
cisTopicObject <- runWarpLDAModels(cisTopicObject, topic=c(7:17), seed=987, nCores=20, iterations = 100, addModels=FALSE)

```
[1] "The number of cores (20) is higher than the number of models (11)."
[1] "Exporting data..."
[1] "Run models..."
 Error in serialize(data, node$con) : error writing to connection
```

How may I debug the error? Would you recommend I move over to pycistopic? Personally, I am better at python than R. To create a cistopic object with pycistopic, do we just need to feed in the regions bed file, fragments.tsv.gz file, and metrics? What does the metrics file look like (ex. A column named cell_barcode)? What are blacklist and valid_bc files?

Sorry, I am new to ATAC analysis.

**Comment by cbravo93** [comment]
Hi!

Can you try lowering the number of cores? cisTopic is deprecated, I'd suggest indeed to move to pycisTopic. You have plenty of tutorials to follow at: https://pycistopic.readthedocs.io/en/latest/

Good luck!

C
