### ISSUE TITLE
Uploading data used in paper

### ISSUE THREAD

**Issue by adamgayoso** [aertslab/cisTopic#8]
Hello,

I was wondering whether it would be possible to upload some of the datasets used in the paper. Namely, I am interested in exploring the processed data (inputs to cisTopic) from the sections "Simulated epigenomes from FACS-sorted bulk ATAC-seq profiles from the hematopoietic system" and "scATAC-seq from FACS-sorted single-cell populations from the hematopoietic system"

Thanks!

**Comment by cbravo93** [comment]
Hi @adamgayoso !

You can find the count matrices from the simulated data sets (by bootstrapping reads from the bulk data from [Corces et al., 2016](https://www.ncbi.nlm.nih.gov/pubmed/27526324)) in this [link](https://send.firefox.com/download/eeac996563604384/#96xzdnntF0WBUDjQTus_ew) (it will expire in 1 day). 

For the FACS-sorted data set, you can find the data (count matrix and peak coordinates) in [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE96769). This is a publicly available data set from [Buenrostro et al., 2018](https://www.sciencedirect.com/science/article/pii/S009286741830446X?via%3Dihub).

For initialising the cisTopic object from a count matrix, you can check that option in [this tutorial](https://rawcdn.githack.com/aertslab/cisTopic/f628c6f60918511ba0fa4a85366ebf52db5940f7/vignettes/CompleteAnalysis.html).

Hope this helps!

C

**Comment by adamgayoso** [comment]
@cbravo93 thank you for the prompt response. Unfortunately the link has already expired, would you mind trying again?

**Comment by cbravo93** [comment]
@adamgayoso Try again [here](https://send.firefox.com/download/59addaaf2fbf1560/#x6C4IWSyOSb5yAGs6Kzy1w).

**Comment by adamgayoso** [comment]
Thank you!
