### ISSUE TITLE
Some data missing for tutorials

### ISSUE THREAD

**Issue by daquang** [aertslab/cisTopic#9]
Some files, like cisTopicObject_pbmc.Rds from the 10X 5k PBMCs and the data/bamfiles/ folder from the melanoma tutorial are missing.

**Comment by JBreunig** [comment]
Somewhat related to this, can you provide a link to the bulk files (e.g. ChIP-seq or ATAC) or more info on the input format required for scoring cells with bulk signatures?  It seems like they are BED files but how are labels generated, from filenames or metadata?

> For example, we can evaluate which cells are more enriched for certain ChIP-seq signatures. First, epigenomic regions are intersected and mapped to regions in the dataset (by default, with at least 40% overlap). 

> # Obtain signatures
> path_to_signatures <- paste0(pathTo10X, 'Bulk_peaks/')
> Bulk_ATAC_signatures <- paste(path_to_signatures, list.files(path_to_signatures), sep='')
> labels  <- gsub('._peaks.narrowPeak', '', list.files(path_to_signatures))

Apologies if I'm missing this info somewhere.
Thanks in advance!
Josh

**Comment by cbravo93** [comment]
Hi!

Until we can put it in our server, you can find the data from the melanoma tutorial [here](https://drive.google.com/drive/folders/18ETGIKgXkILo3Xfv9KuysOMqchmSfFX2?usp=sharing); and the one from the 10X tutorial [here](https://drive.google.com/drive/folders/1QORpLPsXejva3oFhECLrnAh5a7FVmJF1?usp=sharing).

@JBreunig you can also find bed files there. The labels can be generated as you want (e.g. from the path or any arbitrary name, as long as it as a vector with the labels you want in the same order as the file paths). This parameter is mainly for easier visualisation and  usage (so you don't get the entire path to the file when doing an enrichment heatmap but the label instead, for example).

Hope this helps!

C
